sudo: false
language: node_js
node_js: 9

env:
  global:
    - NODE_ENV=production

cache:
  yarn: true
  directories:
    - node_modules # NPM packages

install:
  - yarn install --production=false

script:
  - yarn test
  - yarn run build
